### ISSUE TITLE
Update UML Class Diagram

### ISSUE THREAD

**Issue by DJMaest** [CMPUT301F20T03/OneInfiniteLoop#61]
Don't forget to keep it up to date.

**Comment by JackyH56** [comment]
AddBookFragment
ViewPhotoActivity
MainActivity
RegisterActivity
SetLocationActivity

**Comment by DJMaest** [comment]
book_status
bookIdentifiable
Books
BooksListAdapter
BooksListAdapter_Expand

**Comment by mbelgie** [comment]
EditBookActivity
ViewMapsActivity
MapAdapter
MainActivity
NavigationActivity

**Comment by tonyxli** [comment]
User
UserProfileFragment
EditUserProfile
ViewUserProfile
Notification
notifiable

**Comment by Haren-Venket** [comment]
ScanFragment
ScanActivity
AutofillDescription
HomeFragment
RequestListFragment

**Comment by DJMaest** [comment]
done uml

**Comment by JackyH56** [comment]
done

**Comment by Archit-13** [comment]
done
